apiVersion: v1
kind: Pod
metadata:
  name: coverm
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
